In [7]:
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_hub as hub

In [2]:
pip install tensorflow --upgrade

Requirement already up-to-date: tensorflow in /home/shivani/.local/lib/python3.8/site-packages (2.10.0)


Note: you may need to restart the kernel to use updated packages.


In [6]:
pip install tensorflow_hub

     |████████████████████████████████| 108 kB 2.9 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [12]:
import os
import numpy as np

import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_datasets as tfds

print("Version: ", tf.__version__)
print("Eager mode: ", tf.executing_eagerly())
print("Hub version: ", hub.__version__)
print("GPU is", "available" if tf.config.list_physical_devices("GPU") else "NOT AVAILABLE")

Version:  2.10.0
Eager mode:  True
Hub version:  0.12.0
GPU is NOT AVAILABLE


2022-09-29 13:40:59.065396: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-09-29 13:40:59.065641: W tensorflow/stream_executor/cuda/cuda_driver.cc:263] failed call to cuInit: UNKNOWN ERROR (303)
2022-09-29 13:40:59.065675: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (shivani-Latitude-3420): /proc/driver/nvidia/version does not exist


In [13]:
# Split the training set into 60% and 40% to end up with 15,000 examples
# for training, 10,000 examples for validation and 25,000 examples for testing.
train_data, validation_data, test_data = tfds.load(
    name="imdb_reviews", 
    split=('train[:60%]', 'train[60%:]', 'test'),
    as_supervised=True)

Dl Completed...: 0 url [00:00, ? url/s]
Dl Size...:  59%|█████████████████            | 47/80 [01:03<00:20,  1.58 MiB/s]


Generating train examples...:   3%| | 684/25000 [00:01<00:49, 488.83 examples/s]
Generating train examples...:   5%| | 1368/25000 [00:02<00:21, 1077.36 examples/
Generating train examples...:   8%| | 2051/25000 [00:02<00:13, 1749.61 examples/
Generating train examples...:  11%| | 2744/25000 [00:02<00:08, 2490.65 examples/
Generating train examples...:  13%|▏| 3372/25000 [00:02<00:06, 3101.79 examples/
Generating train examples...:  16%|▏| 4062/25000 [00:02<00:05, 3835.96 examples/
Generating train examples...:  19%|▏| 4742/25000 [00:02<00:04, 4476.42 examples/
Generating train examples...:  22%|▏| 5394/25000 [00:02<00:04, 4833.00 examples/
Generating train examples...:  24%|▏| 6082/25000 [00:02<00:03, 5338.07 examples/
Generating train examples...:  27%|▎| 6781/25000 [00:02<00:03, 5768.34 examples/
Generating train examples...:  30%|▎| 7473/25000 [00:02<00:02, 6079.84 examples/
Generating train examples...:  33%|▎| 8150/25000 [00:03<00:02, 6272.58 examples/
Generating train examples...

Generating train examples...:  73%|▋| 18173/25000 [00:04<00:01, 6162.69 examples
Generating train examples...:  75%|▊| 18826/25000 [00:04<00:00, 6268.25 examples
Generating train examples...:  78%|▊| 19511/25000 [00:04<00:00, 6437.46 examples
Generating train examples...:  81%|▊| 20169/25000 [00:04<00:00, 6478.30 examples
Generating train examples...:  83%|▊| 20843/25000 [00:05<00:00, 6553.82 examples
Generating train examples...:  86%|▊| 21519/25000 [00:05<00:00, 6614.93 examples
Generating train examples...:  89%|▉| 22204/25000 [00:05<00:00, 6684.86 examples
Generating train examples...:  91%|▉| 22873/25000 [00:05<00:00, 6413.65 examples
Generating train examples...:  94%|▉| 23535/25000 [00:05<00:00, 6472.40 examples
Generating train examples...:  97%|▉| 24185/25000 [00:05<00:00, 6193.56 examples
Generating train examples...:  99%|▉| 24863/25000 [00:05<00:00, 6359.92 examples
                                                                                
Shuffling ~/tensorflow_datas

Generating unsupervised examples...:  56%|▌| 28032/50000 [00:07<00:03, 6821.17 e
Generating unsupervised examples...:  57%|▌| 28715/50000 [00:07<00:03, 6736.46 e
Generating unsupervised examples...:  59%|▌| 29389/50000 [00:07<00:03, 6722.80 e
Generating unsupervised examples...:  60%|▌| 30062/50000 [00:07<00:02, 6718.01 e
Generating unsupervised examples...:  61%|▌| 30734/50000 [00:07<00:02, 6717.06 e
Generating unsupervised examples...:  63%|▋| 31406/50000 [00:07<00:02, 6607.24 e
Generating unsupervised examples...:  64%|▋| 32079/50000 [00:07<00:02, 6642.63 e
Generating unsupervised examples...:  65%|▋| 32747/50000 [00:08<00:02, 6653.49 e
Generating unsupervised examples...:  67%|▋| 33440/50000 [00:08<00:02, 6733.32 e
Generating unsupervised examples...:  68%|▋| 34122/50000 [00:08<00:02, 6759.11 e
Generating unsupervised examples...:  70%|▋| 34799/50000 [00:08<00:02, 6467.97 e
Generating unsupervised examples...:  71%|▋| 35476/50000 [00:08<00:02, 6555.38 e
Generating unsupervised exam

Dataset imdb_reviews downloaded and prepared to ~/tensorflow_datasets/imdb_reviews/plain_text/1.0.0. Subsequent calls will reuse this data.


In [14]:
train_examples_batch, train_labels_batch = next(iter(train_data.batch(10)))
train_examples_batch

2022-09-29 13:44:29.867326: W tensorflow/core/kernels/data/cache_dataset_ops.cc:856] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell 

In [15]:
train_labels_batch

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0])>

In [16]:
embedding = "https://tfhub.dev/google/nnlm-en-dim50/2"
hub_layer = hub.KerasLayer(embedding, input_shape=[], 
                           dtype=tf.string, trainable=True)
hub_layer(train_examples_batch[:3])

<tf.Tensor: shape=(3, 50), dtype=float32, numpy=
array([[ 0.5423195 , -0.0119017 ,  0.06337538,  0.06862972, -0.16776837,
        -0.10581174,  0.16865303, -0.04998824, -0.31148055,  0.07910346,
         0.15442263,  0.01488662,  0.03930153,  0.19772711, -0.12215476,
        -0.04120981, -0.2704109 , -0.21922152,  0.26517662, -0.80739075,
         0.25833532, -0.3100421 ,  0.28683215,  0.1943387 , -0.29036492,
         0.03862849, -0.7844411 , -0.0479324 ,  0.4110299 , -0.36388892,
        -0.58034706,  0.30269456,  0.3630897 , -0.15227164, -0.44391504,
         0.19462997,  0.19528408,  0.05666234,  0.2890704 , -0.28468323,
        -0.00531206,  0.0571938 , -0.3201318 , -0.04418665, -0.08550783,
        -0.55847436, -0.23336391, -0.20782952, -0.03543064, -0.17533456],
       [ 0.56338924, -0.12339553, -0.10862679,  0.7753425 , -0.07667089,
        -0.15752277,  0.01872335, -0.08169781, -0.3521876 ,  0.4637341 ,
        -0.08492756,  0.07166859, -0.00670817,  0.12686075, -0.19326553,
 

In [17]:
model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(1))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 keras_layer (KerasLayer)    (None, 50)                48190600  
                                                                 
 dense (Dense)               (None, 16)                816       
                                                                 
 dense_1 (Dense)             (None, 1)                 17        
                                                                 
Total params: 48,191,433
Trainable params: 48,191,433
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [19]:
history = model.fit(train_data.shuffle(10000).batch(512),
                    epochs=10,
                    validation_data=validation_data.batch(512),
                    verbose=1)

Epoch 1/10
30/30 [==============================] - 11s 354ms/step - loss: 0.6805 - accuracy: 0.4983 - val_loss: 0.6432 - val_accuracy: 0.5012
Epoch 2/10
30/30 [==============================] - 10s 340ms/step - loss: 0.5858 - accuracy: 0.5869 - val_loss: 0.5403 - val_accuracy: 0.6963
Epoch 3/10
30/30 [==============================] - 11s 350ms/step - loss: 0.4531 - accuracy: 0.7807 - val_loss: 0.4300 - val_accuracy: 0.7955
Epoch 4/10
30/30 [==============================] - 11s 361ms/step - loss: 0.3270 - accuracy: 0.8682 - val_loss: 0.3609 - val_accuracy: 0.8438
Epoch 5/10
30/30 [==============================] - 10s 343ms/step - loss: 0.2371 - accuracy: 0.9127 - val_loss: 0.3258 - val_accuracy: 0.8610
Epoch 6/10
30/30 [==============================] - 10s 343ms/step - loss: 0.1746 - accuracy: 0.9419 - val_loss: 0.3116 - val_accuracy: 0.8687
Epoch 7/10
30/30 [==============================] - 10s 341ms/step - loss: 0.1262 - accuracy: 0.9620 - val_loss: 0.3081 - val_accuracy: 0.8701

In [20]:
import pickle
with open('text_classification.pickle','wb') as f:
    pickle.dump(history,f)

INFO:tensorflow:Assets written to: ram://8aae080b-95e1-41f8-8502-267530d33552/assets


INFO:tensorflow:Assets written to: ram://8aae080b-95e1-41f8-8502-267530d33552/assets


In [21]:
results = model.evaluate(test_data.batch(512), verbose=2)

for name, value in zip(model.metrics_names, results):
  print("%s: %.3f" % (name, value))

49/49 - 1s - loss: 0.3705 - accuracy: 0.8544 - 1s/epoch - 25ms/step
loss: 0.371
accuracy: 0.854


In [25]:
with open('text_classification.pickle','rb') as f:
    m1 = pickle.load(f)
m1.evaluate(test_data.batch(512))

AttributeError: 'History' object has no attribute 'evaluate'